name: Bump

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * *'


jobs:
  list_crds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: crds
        name: List CRDS
        run: echo crds=$(jq  -c 'keys' config.json) >> ${GITHUB_OUTPUT}
    outputs:
      crds: ${{ steps.crds.outputs.crds }}

  crds_json_schema:
    needs:
      - list_crds
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        crds_name: ${{ fromJson(needs.list_crds.outputs.crds) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: "Install Deps"
        run: pip install ruamel.yaml PyGithub
      - name: generate jsonschema
        run: ./openapi2jsonschema.py ${{ matrix.crds_name }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'build(deps): upgrade CRDS ${{ matrix.crds_name }}'
          commit-message: 'build(deps): upgrade CRDS ${{ matrix.crds_name }}'
          branch: 'bump-${{ matrix.crds_name }}'
          delete-branch: true
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
          repo: juliangruber/approve-pull-request-action # optional
